const { chromium } = require(process.env.TEMP + '/happybite-preview/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({ channel: 'msedge', headless: true });
 const context = await browser.newContext({ viewport: { width: 1296, height: 1000 }, reducedMotion: 'reduce' });
 const page = await context.newPage();
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 page.setDefaultTimeout(10000);
 await page.goto('http://127.0.0.1:5185/katalog');
 assert.equal(await page.getByRole('button', { name: /^Notifikasi/ }).count(), 0);
 assert.equal(await page.getByRole('navigation', { name: 'Navigasi utama', exact: true }).getByRole('link', { name: 'Katalog Menu', exact: true }).locator('svg').count(), 1);
 await page.setViewportSize({ width: 375, height: 812 });
 await page.getByRole('button', { name: 'Buka menu', exact: true }).click();
 assert.equal(await page.getByRole('navigation', { name: 'Navigasi seluler' }).getByRole('link', { name: 'Katalog Menu', exact: true }).locator('svg').count(), 1);
 const account = 'notification@example.com';
 const item = (id, type, read, ownerEmail = account) => ({ id, ownerEmail, type, read, title: type === 'status' ? 'Pesanan #HB-TEST-' + id + ' Sedang Diproses' : 'Info promo contoh pengujian', description: 'Pesanan sudah masuk antrean dapur. Pembayaran menunggu verifikasi.', timestamp: new Date(Date.now() - 600000).toISOString(), ...(type === 'status' ? { linkedOrderId: 'HB-TEST-' + id } : {}) });
 const fixtures = [item('1', 'status', false), item('2', 'status', false), item('3', 'status', true), item('4', 'promo', false), item('private', 'status', false, 'different@example.com')];
 await page.evaluate(({ account, fixtures }) => {
  localStorage.setItem('happybite-auth-v1', JSON.stringify({ isLoggedIn: true, user: { name: 'Notification User', email: account } }));
  localStorage.setItem('happybite-notifications-v1', JSON.stringify(fixtures));
 }, { account, fixtures });
 await page.setViewportSize({ width: 1296, height: 1000 }); await page.reload();
 const bell = () => page.getByRole('button', { name: /^Notifikasi,/ });
 await bell().waitFor();
 assert.equal(await bell().getAttribute('aria-label'), 'Notifikasi, 2 belum dibaca');
 assert.equal(await page.getByRole('navigation', { name: 'Navigasi utama', exact: true }).getByRole('link', { name: 'Katalog Menu', exact: true }).locator('svg').count(), 0);
 const bellBounds = await bell().boundingBox(); const profileBounds = await page.getByRole('button', { name: 'Menu akun Notification User' }).boundingBox();
 assert.ok(bellBounds.x < profileBounds.x && profileBounds.x - bellBounds.x < 80);
 const url = page.url(); await bell().click();
 const modal = () => page.getByRole('dialog', { name: 'Notifikasi & Update Pesanan', exact: true });
 await modal().waitFor(); assert.equal(page.url(), url);
 assert.ok(await modal().evaluate(el => el.matches(':modal')));
 assert.ok(await page.evaluate(() => document.body.classList.contains('overflow-hidden')));
 assert.equal(await modal().locator('li').count(), 3);
 for (const title of ['Semua (3)', 'Status Pesanan (3)']) assert.ok(await modal().getByRole('button', { name: title, exact: true }).isVisible());
 assert.equal(await modal().getByRole('button', { name: /Promo|Voucher/ }).count(), 0);
 assert.ok(await page.evaluate(() => JSON.parse(localStorage.getItem('happybite-notifications-v1')).every(item => item.type === 'status')));
 assert.equal(await modal().getByText('Belum dibaca', { exact: true }).count(), 2);
 assert.equal(await modal().getByText('10 mnt lalu', { exact: true }).count(), 3);
 for (let i = 0; i < 12; i++) { await page.keyboard.press('Tab'); assert.ok(await modal().evaluate(el => el.contains(document.activeElement))); }
 await modal().getByRole('button', { name: 'Status Pesanan (3)', exact: true }).click(); assert.equal(await modal().locator('li').count(), 3);
 await page.keyboard.press('Escape'); assert.equal(await modal().count(), 0);
 assert.ok(await bell().evaluate(el => el === document.activeElement));
 assert.ok(await page.evaluate(() => !document.body.classList.contains('overflow-hidden')));
 await bell().click(); await page.mouse.click(5, 5); assert.equal(await modal().count(), 0);
 await bell().click(); await modal().getByRole('button', { name: 'Tutup notifikasi' }).click(); assert.equal(await modal().count(), 0);
 await bell().click();
 await modal().getByRole('link', { name: /Lihat Rincian Pesanan/ }).first().click();
 await page.waitForURL('**/riwayat-pesanan');
 assert.equal(await modal().count(), 0);
 await page.getByRole('button', { name: 'Notifikasi, 1 belum dibaca', exact: true }).waitFor();
 await bell().click(); await modal().getByRole('button', { name: /Tandai Semua Dibaca/ }).click();
 assert.ok(await modal().getByText('0 Baru', { exact: true }).isVisible());
 assert.equal(await modal().getByText('Belum dibaca', { exact: true }).count(), 0);
 await page.keyboard.press('Escape'); assert.equal(await bell().locator('span').count(), 0);
 await page.reload(); await page.getByRole('button', { name: 'Notifikasi, 0 belum dibaca', exact: true }).waitFor();
 const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('happybite-notifications-v1')));
 assert.ok(saved.filter(i => i.ownerEmail === account).every(i => i.read));
 assert.equal(saved.find(i => i.ownerEmail === 'different@example.com').read, false);
 // Exercise a long list and independent scrolling at desktop and mobile sizes.
 const many = [...fixtures, ...Array.from({ length: 20 }, (_, index) => item('long-' + index, 'status', true))];
 await page.evaluate(many => localStorage.setItem('happybite-notifications-v1', JSON.stringify(many)), many); await page.reload(); await bell().click();
 for (const width of [320, 375, 768, 1024, 1296, 1536]) {
  await page.setViewportSize({ width, height: 812 });
  const box = await modal().boundingBox();
  assert.ok(box.x >= 15 && box.x + box.width <= width - 15);
  assert.ok(box.y >= 0 && box.y + box.height <= 813);
  assert.ok(await modal().evaluate(el => el.scrollWidth <= el.clientWidth));
  const list = modal().locator('.overflow-y-auto');
  assert.ok(await list.evaluate(el => el.scrollHeight > el.clientHeight));
  await list.evaluate(el => { el.scrollTop = 300; });
  assert.ok(await list.evaluate(el => el.scrollTop > 0));
 }
 await page.setViewportSize({ width: 1296, height: 1000 });
 await modal().locator('.overflow-y-auto').evaluate(el => { el.scrollTop = 0; });
 await page.screenshot({ path: 'D:/happybite-web/.artifacts/notifications-desktop.png' });
 await page.setViewportSize({ width: 375, height: 812 });
 await page.screenshot({ path: 'D:/happybite-web/.artifacts/notifications-mobile.png' });
 await page.keyboard.press('Escape');
 await page.evaluate(() => localStorage.setItem('happybite-auth-v1', JSON.stringify({ isLoggedIn: true, user: { name: 'Different', email: 'different@example.com' } }))); await page.reload();
 await page.getByRole('button', { name: 'Notifikasi, 1 belum dibaca', exact: true }).click();
 assert.equal(await modal().locator('li').count(), 1);
 await page.keyboard.press('Escape');
 await page.evaluate(() => localStorage.removeItem('happybite-auth-v1')); await page.goto('http://127.0.0.1:5185/');
 assert.equal(await bell().count(), 0);
 assert.deepEqual(errors, []);
 console.log('PASS guest/member navbar, lock icons, badge/filter counts, modal dismissal/focus trap, links, read persistence/account isolation, long-list scrolling 320–1536px');
 await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
